import { readFileSync } from 'node:fs'
import { resolve } from 'node:path'
import { describe, expect, it } from 'vitest'

const source = readFileSync(resolve(process.cwd(), 'src/preload/index.ts'), 'utf8')

describe('V2 preload API', () => {
  it('只暴露 V2 API 和 v2 IPC 通道，不再暴露 V1 写入通道', () => {
    expect(source).toContain("exposeInMainWorld('yumiV2', yumiV2)")
    expect(source).toContain("ipcRenderer.invoke('v2:products:expected-profit'")
    expect(source).toContain("ipcRenderer.invoke('v2:orders:create'")
    expect(source).toContain("ipcRenderer.invoke('v2:orders:record-fund'")
    expect(source).toContain("ipcRenderer.invoke('v2:order-fund-proofs:pick'")
    expect(source).toContain("ipcRenderer.invoke('v2:order-fund-proofs:get'")
    expect(source).toContain("ipcRenderer.invoke('v2:order-fund-proofs:attach'")
    expect(source).toContain("ipcRenderer.invoke('v2:order-fund-proofs:open'")
    expect(source).toContain("ipcRenderer.invoke('v2:fulfillment:assignments:create'")
    expect(source).toContain("ipcRenderer.invoke('v2:fulfillment:assignments:status'")
    expect(source).toContain("ipcRenderer.invoke('v2:fulfillment:tasks:result:get'")
    expect(source).toContain("ipcRenderer.invoke('v2:fulfillment:making-reviews:create'")
    expect(source).toContain("ipcRenderer.invoke('v2:fulfillment:making-reviews:correct'")
    expect(source).toContain("ipcRenderer.invoke('v2:fulfillment:making-reviews:void'")
    expect(source).toContain("ipcRenderer.invoke('v2:product-inventory:allocations:create'")
    expect(source).toContain("ipcRenderer.invoke('v2:work-time-reviews:candidates:list'")
    expect(source).toContain("ipcRenderer.invoke('v2:work-time-reviews:create'")
    expect(source).toContain("ipcRenderer.invoke('v2:work-time-reviews:correct'")
    expect(source).not.toContain("ipcRenderer.invoke('v2:fulfillment:opening-wip:record'")
    expect(source).not.toContain("ipcRenderer.invoke('v2:fulfillment:results:submit'")
    expect(source).not.toContain("ipcRenderer.invoke('v2:fulfillment:inspections:confirm'")
    expect(source).not.toContain("ipcRenderer.invoke('v2:work-time-reviews:drafts:create'")
    expect(source).not.toContain("ipcRenderer.invoke('v2:work-time-reviews:confirm'")
    expect(source).toContain("ipcRenderer.invoke('v2:workers:create'")
    expect(source).toContain("ipcRenderer.invoke('v2:workers:wages:record'")
    expect(source).toContain("ipcRenderer.invoke('v2:settlements:drafts:create'")
    expect(source).toContain("ipcRenderer.invoke('v2:settlements:drafts:update'")
    expect(source).toContain("ipcRenderer.invoke('v2:settlements:confirm'")
    expect(source).toContain("ipcRenderer.invoke('v2:finance:manual-income:create'")
    expect(source).toContain("ipcRenderer.invoke('v2:finance:reimbursements:create'")
    expect(source).toContain("ipcRenderer.invoke('v2:after-sales:cases:create'")
    expect(source).toContain("ipcRenderer.invoke('v2:after-sales:charges:link'")
    expect(source).toContain("ipcRenderer.invoke('v2:reports:customers:insights:list'")
    expect(source).toContain("ipcRenderer.invoke('v2:reports:customers:insights:get'")
    expect(source).toContain("ipcRenderer.invoke('v2:reports:capacity-risk:get'")
    expect(source).toContain("ipcRenderer.invoke('v2:reports:delivery-risk:get'")
    expect(source).not.toContain("exposeInMainWorld('yumi',")
    expect(source).not.toContain("ipcRenderer.invoke('orders:create'")
  })
})
